plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety
  - rubocop-packaging
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - lib/typesense_mock_client.rb

inherit_mode:
  merge:
    - Exclude

Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - lib/tasks/load_mx_postal_codes.rake
    - test/factories/*.rb
    - test/controllers/**/*.rb
    - test/models/**/*.rb
    - test/helpers/search_helper_test.rb
Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb
Metrics/ClassLength:
  Exclude:
   - test/controllers/**/*.rb
   - test/models/concerns/searchable_test.rb
   - test/models/stock_reservation_test.rb

# Rails rubocop configuration
Rails/DynamicFindBy:
  Exclude:
    - app/controllers/passwords_controller.rb
Rails/SkipsModelValidations:
  Exclude:
    - lib/tasks/load_mx_postal_codes.rake
Rails/NotNullColumn:
  Exclude:
    - db/migrate/20250505204053_add_columns_to_addresses.rb
Rails/ApplicationController:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
