plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety

require: rubocop-packaging

Style/Documentation:
  Enabled: false

# Rails rubocop configuration
Rails/DynamicFindBy:
  Exclude:
    - app/controllers/passwords_controller.rb
