plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety
  - rubocop-packaging
  - rubocop-factory_bot

Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - lib/tasks/load_mx_postal_codes.rake
Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

# Rails rubocop configuration
Rails/DynamicFindBy:
  Exclude:
    - app/controllers/passwords_controller.rb
Rails/SkipsModelValidations:
  Exclude:
    - lib/tasks/load_mx_postal_codes.rake
Rails/NotNullColumn:
  Exclude:
    - db/migrate/20250505204053_add_columns_to_addresses.rb
