plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety
  - rubocop-packaging
  - rubocop-factory_bot

Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - config/environments/production.rb


# Rails rubocop configuration
Rails/DynamicFindBy:
  Exclude:
    - app/controllers/passwords_controller.rb
